### ISSUE TITLE
Webhooks Interface Error

### ISSUE THREAD

**Issue by beckbailey** [craftcms/shopify#84]
### Description
I've configured the plugin and input the connection settings. When I get to the webhooks step in the documentation I get an error when I try to visit that interface in the CP. I have a multi-site configuration. I tried inputting the API values directly in the interface and as variables in my env file. Stack trace attached.
[shopify-trace.txt](https://github.com/craftcms/shopify/files/12937299/shopify-trace.txt)

### Steps to reproduce

See above

### Additional info

- Craft version: 4.5.6.1
- PHP version: 8.0.26
- Database driver & version: MySQL 5.7.41
- Plugins & versions: Shopify 3.2.0

**Comment by nfourtythree** [comment]
Hi @beckbailey 

Which "Webhook version" did you set in your custom develop app in your Shopify store?

Thanks

**Comment by beckbailey** [comment]
@nfourtythree I tried all that I have available to me with no success. Right now it's set to 
2023-10. Here's what I can select from:
<img width="293" alt="Screenshot_34" src="https://github.com/craftcms/shopify/assets/1824287/bf035129-25e8-4d6e-ac31-1f7e34a9a4a0">

**Comment by nfourtythree** [comment]
@beckbailey ah yes I can see that they have finally dropped support for `2022-10` for newly created apps.

We were waiting on this issue to be resolved in the Shopify PHP API: https://github.com/Shopify/shopify-api-php/issues/300

That has now been resolved, so we have started our process to get a new release out of this plugin so it can be compatible. We are looking to get that out ASAP.

If you are in desperate need for this right now you can change your `craftcms/shopify` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/shopify": "4.0.x-dev as 4.0.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lukeholder** [comment]
This is fixed for the next release. I will update this issue once Shopify 4.0 is out.

**Comment by lukeholder** [comment]
4.0.0 is now out. Make sure to read the [changelog item](https://github.com/craftcms/shopify/blob/develop/CHANGELOG.md#400---2023-11-02) to learn what you need to do to upgrade. The readme also [contains instructions](https://github.com/craftcms/shopify#upgrading).

**Comment by beckbailey** [comment]
I just got back to this and it's still not working for me. 
I attached my error. I checked and regenerated my credentials multiple times. My host name did change on my Shopify install since my initial post but I have updated it in the Craft config.

[error-shopify.txt](https://github.com/craftcms/shopify/files/14116240/error-shopify.txt)

CraftCMS: 4.7.1
Shopify: 4.0
PHP version: 8.0.26
Database driver & version: MySQL 5.7.41
